version: '2'
services:

  postgres:
    image: postgres:9.5.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  app:
    build: .
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    links:
      - postgres
    depends_on:
      - postgres
