"""empty message

Revision ID: 4f22f48975a0
Revises: 721e53612e84
Create Date: 2016-07-25 15:31:51.370110

"""

# revision identifiers, used by Alembic.
revision = '4f22f48975a0'
down_revision = '721e53612e84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issuer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.String(length=255), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subject_id')
        batch_op.drop_column('issuer_id')

    ### end Alembic commands ###
