"""empty message

Revision ID: 513803e6f38c
Revises: 4f22f48975a0
Create Date: 2016-08-01 17:57:35.080993

"""

# revision identifiers, used by Alembic.
revision = '513803e6f38c'
down_revision = '4f22f48975a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('status_msg', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_payment'))
    )
    with op.batch_alter_table('suit', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_suit_payment_id_payment'), 'payment', ['payment_id'], ['reference'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_suit_payment_id_payment'), type_='foreignkey')

    op.drop_table('payment')
    ### end Alembic commands ###
